# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Domů"
#   url = ""
#   weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

[[main]]
  name = "Jak můžu pomoct?"  # A link title for your page.
  url = "#uvod"  # The URL of your page.
  weight = 10  # The position of your page in the menu.

[[main]]
  name = "Aktuality"
  identifier = "#post"
  weight = 20

# [[main]]
#   name = "Územní plán Čerčan"
#   identifier = "plan"
#   url = "plan/"
#   weight = 50

# [[main]]
#   name = "Územní plán"
#   parent = "plan"
#   url = "plan/uzemni-plan/"
#   weight = 51

# [[main]]
#   name = "Změna č. 1"
#   parent = "plan"
#   url = "plan/zmena/"
#   weight = 52

[[main]]
  name = "Soubory ke stažení"
  # parent = "plan"
  # url = "plan/soubory/"
  url = "#soubory"
  weight = 30

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 40

[[main]]
  name = "O spolku"
  url = "aktuality/zalozeni-spolku/"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
