backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Aktuality"
    name: "aktuality" # Used in routes, e.g., /admin/collections/blog
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Podnadpis", name: "subtitle", widget: "string"}
      - {label: "Shrnutí", name: "summary", widget: "string"}
      - {label: "Datum", name: "date", widget: date}
      - {label: "Obsah", name: "body", widget: "markdown"}
      - {label: "projects", name: "projects", widget: "hidden"}
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Územní plán"
        name: "uzemni-plan"
        file: "content/plan/uzemni-plan.md"
        fields:
        - {label: "Nadpis", name: "title", widget: "string"}
        - {label: "Podnadpis", name: "subtitle", widget: "string"}
        - {label: "Shrnutí", name: "summary", widget: "string"}
        - {label: "Datum", name: "date", widget: date}
        - {label: "Obsah", name: "body", widget: "markdown"}
        - {label: "projects", name: "projects", widget: "hidden"}
      - label: "Změna č. 1"
        name: "zmenac1"
        file: "content/zmena.md"
        fields:
        - {label: "Nadpis", name: "title", widget: "string"}
        - {label: "Podnadpis", name: "subtitle", widget: "string"}
        - {label: "Shrnutí", name: "summary", widget: "string"}
        - {label: "Datum", name: "date", widget: date}
        - {label: "Obsah", name: "body", widget: "markdown"}
        - {label: "projects", name: "projects", widget: "hidden"}
      - label: Soubory ke stažení"
        name: "soubory"
        file: "content/soubory.md"
        fields:
        - {label: "Nadpis", name: "title", widget: "string"}
        - {label: "Podnadpis", name: "subtitle", widget: "string"}
        - {label: "Shrnutí", name: "summary", widget: "string"}
        - {label: "Datum", name: "date", widget: date}
        - {label: "Obsah", name: "body", widget: "markdown"}
        - {label: "projects", name: "projects", widget: "hidden"}
