backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Aktulity" # Used in the UI
    name: "aktuality" # Used in routes, e.g., /admin/collections/blog
    folder: "content/aktuality" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Podnadpis", name: "summary", widget: "string"}
      - {label: "Datum", name: "date", widget: date}
      - {label: "Obrázek", name: "image", widget: image}
      - {label: "Obsah", name: "body", widget: "markdown"}
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Hlavní stránka"
        name: "index"
        file: "content/_index.md"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt.md"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: "Můj email", name: userEmail, widget: string}
          - {label: "Moje jméno", name: userName, widget: string}
          - {label: "Můj telefon", name: userPhone, widget: string}
          - {label: "Nadpis formuláře", name: formTitle, widget: string}
          - {label: "Nápověda v poli Jméno", name: visitorName, widget: string}
          - {label: "Nápověda v poli Číslo", name: visitorPhone, widget: string}
          - {label: "Nápověda v poli E-Mail", name: visitorEmail, widget: string}
          - {label: "Nápověda v poli Text", name: visitorText, widget: string}
      - label: "Beauty odchovy"
        name: "beauty-odchovy"
        file: "content/beauty-odchovy.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Beauty zdraví"
        name: "beauty-zdravi"
        file: "content/beauty-zdravi.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Beauty úspěchy"
        name: "beauty-uspechy"
        file: "content/beauty-uspechy.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Bak potomci"
        name: "bak-potomci"
        file: "content/bak-potomci.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Bak zdraví"
        name: "bak-zdravi"
        file: "content/bak-zdravi.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - label: "Bak úspěchy"
        name: "bak-uspechy"
        file: "content/bak-uspechy.md"
        fields:
          - {label: Nadpis, name: title, widget: hidden}
          - {label: Nadpis, name: fullTitle, widget: string}
          - {label: layout, name: layout, widget: hidden}
          - {label: popis, name: popis, widget: hidden}
          - {label: firstButtonName, name: firstButtonName, widget: hidden}
          - {label: firstButtonLink, name: firstButtonLink, widget: hidden}
          - {label: secondButtonName, name: secondButtonName, widget: hidden}
          - {label: secondButtonLink, name: secondButtonLink, widget: hidden}
          - {label: thirdButtonName, name: thirdButtonName, widget: hidden}
          - {label: thirdButtonLink, name: thirdButtonLink, widget: hidden}
          - {label: "Obsah", name: "body", widget: "markdown"}

