backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Územní plán"
        name: "uzemni-plan"
        file: "content/plan/uzemni-plan.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
